name: Build, Test, and Publish

on:
  push:
    branches: [ "main" ]
    tags:
      - v*
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: "1.0.0"
      skip_tests:
        description: 'Skip tests'
        required: false
        default: false
        type: boolean
      publish_package:
        description: 'Publish NuGet package'
        required: false
        default: false
        type: boolean

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: ${{ !inputs.skip_tests }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: |
          dotnet test tests/LBinarySerializer.Tests/ \
          --configuration Release \
          --no-build \
          --verbosity normal \
          --logger "console;vebosity=detailed"
  build:
    runs-on: ubuntu-latest
    needs: test
    if: always() && (needs.test.result == 'success' || inputs.skip_tests)

    outputs:
      package-version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Determine version
        id: version
        run: |
          if [[ "${{ github.event_name}}" == "workflow_dispatch" ]]; then
            VERSION="${{ inputs.version }}"
          elif [[ ${{ github.ref }} == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            VERSION="0.1.0-ci-$(date +%Y%m%d%H%M%S)"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Package version: $VERSION"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet build src/ \
          --configuration Release \
          --no-restore
          -p:Version=${{ steps.version.outputs.version }}

      - name: Pack
        run: |
          dotnet pack src/ \
          --configuration Release \
          --no-restore \
          --output ./artifacts \
          -p:PackageVersion=${{ steps.version.outputs.version }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: ./artifacts/*.nupkg
          retention-days: 30

  publish:
    name: Publish to NuGet
    runs-on: ubuntu-latest
    needs: [test, build]
    if: |
      always() &&
      (needs.test.result == 'success' || inputs.skip_tests) &&
      needs.build.result == 'success' &&
      (
        (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v' )) ||
        (github.event_name == 'workflow_dispatch' && inputs.publish_package)
      )

    environment: production

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: nuget-packages
          path: ./artifacts

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish to NuGet
        run: |
          echo "Publish to nuget version $VERSION"
